[build]
  command = "npm run build"
  functions = "functions" # netlify dev uses this directory to scaffold and serve your functions
  publish = "out"

# note: each of these fields are OPTIONAL, with an exception that when you're specifying "command" and "port", you must specify framework = "#custom"
[dev]
  framework = "next"
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "public" # The path to your static content folder
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser